# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        dependency-type: "development"
      tree-sitter:
        patterns:
          - "tree-sitter*"
      minor:
        update-types:
          - "minor"
          - "patch"
      aws:
        patterns:
          - "aws"
      apache-arrow:
        patterns:
          - "arrow*"
          - "lancedb*"
          - "parquet*"
      macros:
        patterns:
          - "quote"
          - "syn"
          - "darling"
          - "proc-macro2"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
