[env]
CMAKE_POLICY_VERSION_MINIMUM = "3.10"
############### SYSTEM SPECIFIC  ###########################################
# Use lld for faster linking
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Enable parallel compilation using all available cores

# Use sparse registry for faster dependency resolution
[registries.crates-io]
protocol = "sparse"
