/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnotationQueueItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "queueId")]
    pub queue_id: String,
    #[serde(rename = "objectId")]
    pub object_id: String,
    #[serde(rename = "objectType")]
    pub object_type: models::AnnotationQueueObjectType,
    #[serde(rename = "status")]
    pub status: models::AnnotationQueueStatus,
    #[serde(rename = "completedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<String>>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl AnnotationQueueItem {
    pub fn new(id: String, queue_id: String, object_id: String, object_type: models::AnnotationQueueObjectType, status: models::AnnotationQueueStatus, created_at: String, updated_at: String) -> AnnotationQueueItem {
        AnnotationQueueItem {
            id,
            queue_id,
            object_id,
            object_type,
            status,
            completed_at: None,
            created_at,
            updated_at,
        }
    }
}

