/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiKeyList : List of API keys for a project
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyList {
    #[serde(rename = "apiKeys")]
    pub api_keys: Vec<models::ApiKeySummary>,
}

impl ApiKeyList {
    /// List of API keys for a project
    pub fn new(api_keys: Vec<models::ApiKeySummary>) -> ApiKeyList {
        ApiKeyList {
            api_keys,
        }
    }
}

