/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BooleanScoreV1 {
    /// The numeric value of the score. Equals 1 for \"True\" and 0 for \"False\"
    #[serde(rename = "value")]
    pub value: f64,
    /// The string representation of the score value. Is inferred from the numeric value and equals \"True\" or \"False\"
    #[serde(rename = "stringValue")]
    pub string_value: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "traceId")]
    pub trace_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "source")]
    pub source: models::ScoreSource,
    #[serde(rename = "observationId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub observation_id: Option<Option<String>>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "authorUserId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author_user_id: Option<Option<String>>,
    #[serde(rename = "comment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Option<String>>,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<serde_json::Value>>,
    /// Reference a score config on a score. When set, config and score name must be equal and value must comply to optionally defined numerical range
    #[serde(rename = "configId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config_id: Option<Option<String>>,
    /// Reference an annotation queue on a score. Populated if the score was initially created in an annotation queue.
    #[serde(rename = "queueId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub queue_id: Option<Option<String>>,
    /// The environment from which this score originated. Can be any lowercase alphanumeric string with hyphens and underscores that does not start with 'langfuse'.
    #[serde(rename = "environment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub environment: Option<Option<String>>,
}

impl BooleanScoreV1 {
    pub fn new(value: f64, string_value: String, id: String, trace_id: String, name: String, source: models::ScoreSource, timestamp: String, created_at: String, updated_at: String) -> BooleanScoreV1 {
        BooleanScoreV1 {
            value,
            string_value,
            id,
            trace_id,
            name,
            source,
            observation_id: None,
            timestamp,
            created_at,
            updated_at,
            author_user_id: None,
            comment: None,
            metadata: None,
            config_id: None,
            queue_id: None,
            environment: None,
        }
    }
}

