/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkConfig {
    #[serde(rename = "supported")]
    pub supported: bool,
    #[serde(rename = "maxOperations")]
    pub max_operations: i32,
    #[serde(rename = "maxPayloadSize")]
    pub max_payload_size: i32,
}

impl BulkConfig {
    pub fn new(supported: bool, max_operations: i32, max_payload_size: i32) -> BulkConfig {
        BulkConfig {
            supported,
            max_operations,
            max_payload_size,
        }
    }
}

