/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChatMessageWithPlaceholders {
    ChatMessageWithPlaceholdersOneOf(Box<models::ChatMessageWithPlaceholdersOneOf>),
    ChatMessageWithPlaceholdersOneOf1(Box<models::ChatMessageWithPlaceholdersOneOf1>),
}

impl Default for ChatMessageWithPlaceholders {
    fn default() -> Self {
        Self::ChatMessageWithPlaceholdersOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "chatmessage")]
    Chatmessage,
    #[serde(rename = "placeholder")]
    Placeholder,
}

impl Default for Type {
    fn default() -> Type {
        Self::Chatmessage
    }
}

