/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateScoreValue : The value of the score. Must be passed as string for categorical scores, and numeric for boolean and numeric scores
/// The value of the score. Must be passed as string for categorical scores, and numeric for boolean and numeric scores
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateScoreValue {
    Number(f64),
    String(String),
}

impl Default for CreateScoreValue {
    fn default() -> Self {
        Self::Number(Default::default())
    }
}

