/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMediaUploadUrlResponse {
    /// The presigned upload URL. If the asset is already uploaded, this will be null
    #[serde(rename = "uploadUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub upload_url: Option<Option<String>>,
    /// The unique langfuse identifier of a media record
    #[serde(rename = "mediaId")]
    pub media_id: String,
}

impl GetMediaUploadUrlResponse {
    pub fn new(media_id: String) -> GetMediaUploadUrlResponse {
        GetMediaUploadUrlResponse {
            upload_url: None,
            media_id,
        }
    }
}

