/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetScoresResponseData {
    GetScoresResponseDataOneOf(Box<models::GetScoresResponseDataOneOf>),
    GetScoresResponseDataOneOf1(Box<models::GetScoresResponseDataOneOf1>),
    GetScoresResponseDataOneOf2(Box<models::GetScoresResponseDataOneOf2>),
}

impl Default for GetScoresResponseData {
    fn default() -> Self {
        Self::GetScoresResponseDataOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "BOOLEAN")]
    Boolean,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::Boolean
    }
}

