/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembershipResponse {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "role")]
    pub role: models::MembershipRole,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl MembershipResponse {
    pub fn new(user_id: String, role: models::MembershipRole, email: String, name: String) -> MembershipResponse {
        MembershipResponse {
            user_id,
            role,
            email,
            name,
        }
    }
}

