/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OpenAiUsage : Usage interface of OpenAI for improved compatibility.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenAiUsage {
    #[serde(rename = "promptTokens", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prompt_tokens: Option<Option<i32>>,
    #[serde(rename = "completionTokens", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completion_tokens: Option<Option<i32>>,
    #[serde(rename = "totalTokens", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_tokens: Option<Option<i32>>,
}

impl OpenAiUsage {
    /// Usage interface of OpenAI for improved compatibility.
    pub fn new() -> OpenAiUsage {
        OpenAiUsage {
            prompt_tokens: None,
            completion_tokens: None,
            total_tokens: None,
        }
    }
}

