/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromptVersionUpdateRequest {
    /// New labels for the prompt version. Labels are unique across versions. The \"latest\" label is reserved and managed by Langfuse.
    #[serde(rename = "newLabels")]
    pub new_labels: Vec<String>,
}

impl PromptVersionUpdateRequest {
    pub fn new(new_labels: Vec<String>) -> PromptVersionUpdateRequest {
        PromptVersionUpdateRequest {
            new_labels,
        }
    }
}

