/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceTypesResponse {
    #[serde(rename = "schemas")]
    pub schemas: Vec<String>,
    #[serde(rename = "totalResults")]
    pub total_results: i32,
    #[serde(rename = "Resources")]
    pub resources: Vec<models::ResourceType>,
}

impl ResourceTypesResponse {
    pub fn new(schemas: Vec<String>, total_results: i32, resources: Vec<models::ResourceType>) -> ResourceTypesResponse {
        ResourceTypesResponse {
            schemas,
            total_results,
            resources,
        }
    }
}

