/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScoreConfig : Configuration for a score
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScoreConfig {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "projectId")]
    pub project_id: String,
    #[serde(rename = "dataType")]
    pub data_type: models::ScoreDataType,
    /// Whether the score config is archived. Defaults to false
    #[serde(rename = "isArchived")]
    pub is_archived: bool,
    /// Sets minimum value for numerical scores. If not set, the minimum value defaults to -∞
    #[serde(rename = "minValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_value: Option<Option<f64>>,
    /// Sets maximum value for numerical scores. If not set, the maximum value defaults to +∞
    #[serde(rename = "maxValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_value: Option<Option<f64>>,
    /// Configures custom categories for categorical scores
    #[serde(rename = "categories", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Option<Vec<models::ConfigCategory>>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl ScoreConfig {
    /// Configuration for a score
    pub fn new(id: String, name: String, created_at: String, updated_at: String, project_id: String, data_type: models::ScoreDataType, is_archived: bool) -> ScoreConfig {
        ScoreConfig {
            id,
            name,
            created_at,
            updated_at,
            project_id,
            data_type,
            is_archived,
            min_value: None,
            max_value: None,
            categories: None,
            description: None,
        }
    }
}

