/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScoreV1 {
    ScoreV1OneOf(Box<models::ScoreV1OneOf>),
    ScoreV1OneOf1(Box<models::ScoreV1OneOf1>),
    ScoreV1OneOf2(Box<models::ScoreV1OneOf2>),
}

impl Default for ScoreV1 {
    fn default() -> Self {
        Self::ScoreV1OneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "BOOLEAN")]
    Boolean,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::Boolean
    }
}

