/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TraceDeleteMultipleRequest {
    /// List of trace IDs to delete
    #[serde(rename = "traceIds")]
    pub trace_ids: Vec<String>,
}

impl TraceDeleteMultipleRequest {
    pub fn new(trace_ids: Vec<String>) -> TraceDeleteMultipleRequest {
        TraceDeleteMultipleRequest {
            trace_ids,
        }
    }
}

