/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserMeta {
    #[serde(rename = "resourceType")]
    pub resource_type: String,
    #[serde(rename = "created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created: Option<Option<String>>,
    #[serde(rename = "lastModified", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_modified: Option<Option<String>>,
}

impl UserMeta {
    pub fn new(resource_type: String) -> UserMeta {
        UserMeta {
            resource_type,
            created: None,
            last_modified: None,
        }
    }
}

